"use client";

import { useTheme } from "next-themes";
import { useEffect, useState } from "react";
import { codeToHtml } from "shiki";

export function CodeBlock({
  code,
  language = "cpp",
}: {
  code: string;
  language?: string;
}) {
  const { resolvedTheme } = useTheme();
  const [html, setHtml] = useState<string | null>(null);
  const theme =
    resolvedTheme === "light" ? "github-light-default" : "github-dark-default";

  useEffect(() => {
    let cancelled = false;
    setHtml(null);

    codeToHtml(code, {
      lang: language,
      theme,
    })
      .then((value) => {
        if (!cancelled) {
          setHtml(value);
        }
      })
      .catch(() => {
        if (!cancelled) {
          setHtml("");
        }
      });

    return () => {
      cancelled = true;
    };
  }, [code, language, theme]);

  if (html === null || html === "") {
    return (
      <pre className="overflow-x-auto rounded-2xl border border-border/70 bg-slate-950/95 p-5 text-slate-50 shadow-[0_16px_40px_-28px_rgba(15,23,42,0.9)]">
        <code className="text-sm font-mono">{code}</code>
      </pre>
    );
  }

  return (
    <div
      className="overflow-hidden rounded-2xl border border-border/70 shadow-[0_16px_40px_-28px_rgba(15,23,42,0.55)] [&_.shiki]:!m-0 [&_.shiki]:overflow-x-auto [&_.shiki]:!rounded-none [&_.shiki]:!p-5 [&_.shiki]:text-sm [&_code]:text-sm"
      // biome-ignore lint: html is generated by shiki from code content, not user input
      dangerouslySetInnerHTML={{ __html: html }}
    />
  );
}
