"use client";

import { useEffect, useState } from "react";
import { codeToHtml } from "shiki";

export function CodeBlock({
  code,
  language = "cpp",
}: {
  code: string;
  language?: string;
}) {
  const [html, setHtml] = useState<string | null>(null);

  useEffect(() => {
    codeToHtml(code, {
      lang: language,
      theme: "github-dark-default",
    }).then(setHtml);
  }, [code, language]);

  if (!html) {
    return (
      <pre className="rounded-lg bg-muted border border-border p-4 overflow-x-auto">
        <code className="text-sm font-mono">{code}</code>
      </pre>
    );
  }

  return (
    <div
      className="[&_pre]:rounded-lg [&_pre]:border [&_pre]:border-border [&_pre]:p-4 [&_pre]:overflow-x-auto [&_pre]:text-sm [&_code]:text-sm"
      // biome-ignore lint: html is generated by shiki from code content, not user input
      dangerouslySetInnerHTML={{ __html: html }}
    />
  );
}
